### ISSUE TITLE
Table markdown style support

### ISSUE THREAD

**Issue by dillingham** [tightenco/novapackages-issues#49]
```css
.markdown th { background: #dae1e7; }
.markdown td { padding: 5px; }
.markdown tr:nth-child(even) { background: #eff3f7; }
.markdown tr:nth-child(odd) { background: #ffffff; }
```
before
![example](https://user-images.githubusercontent.com/29180903/51066542-cbedf680-15d8-11e9-9994-186547918f9d.png)

after
![after](https://user-images.githubusercontent.com/29180903/51066690-ac0b0280-15d9-11e9-9119-7bc8db4bf0ac.png)
